name = "rabbitsearch3"
main = "src/index.js"
compatibility_date = "2023-10-13"

[[kv_namespaces]]
binding = "KV"
id = "67c6c16db0e1423a83c52a3a6204cb47"

[vars]
# Don't forget to set the brave api key with: wrangler secret put BRAVE_SEARCH_KEY